set_property PACKAGE_PIN E3 [get_ports CLK_100_i]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_100_i]
create_clock -period 10 -name CLK_100 [get_ports CLK_100_i]

set_property PACKAGE_PIN F4 [get_ports CLK_200_i]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_200_i]
create_clock -period 5 -name CLK_200 [get_ports CLK_200_i]

set_property PACKAGE_PIN H5 [get_ports EXAMPLE1_i]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE1_i]
set_property PACKAGE_PIN J5 [get_ports EXAMPLE2_i]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE2_i]
set_property PACKAGE_PIN T9 [get_ports EXAMPLE3_i]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE3_i]
set_property PACKAGE_PIN T10 [get_ports EXAMPLE1_o]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE1_o]
set_property PACKAGE_PIN G6 [get_ports EXAMPLE2_o]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE2_o]
set_property PACKAGE_PIN F6 [get_ports EXAMPLE3_o]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE3_o]
